# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_INN_QT_INPUT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_INN_QT_INPUT.setGeometry(QtCore.QRect(120, 70, 211, 31))
        self.lineEdit_INN_QT_INPUT.setObjectName("lineEdit_INN_QT_INPUT")
        self.lineEdit_NAME_organization = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_NAME_organization.setGeometry(QtCore.QRect(480, 70, 231, 31))
        self.lineEdit_NAME_organization.setObjectName("lineEdit_NAME_organization")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 40, 91, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_Record_to_Excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Record_to_Excel.setGeometry(QtCore.QRect(490, 190, 111, 21))
        self.pushButton_Record_to_Excel.setObjectName("pushButton_Record_to_Excel")
        self.pushButton_Parse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Parse.setGeometry(QtCore.QRect(70, 140, 131, 31))
        self.pushButton_Parse.setObjectName("pushButton_Parse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ИНН"))
        self.label_2.setText(_translate("MainWindow", "Название ООО"))
        self.pushButton_Record_to_Excel.setText(_translate("MainWindow", "Запись в excel"))
        self.pushButton_Parse.setText(_translate("MainWindow", "Заполнить по ИНН"))
